### ISSUE TITLE
Pinout diagram of HAT

### ISSUE THREAD

**Issue by CamDavidsonPilon** [Pioreactor/hardware#20]
https://github.com/j0ono0/pinout

https://github.com/yaqwsx/PcbDraw

**Comment by VitorFrost** [comment]
Can you post here at list the circuit diagram? anything? 
I just want to understand a little more how things are connected, and what sensors are used.
I do believe I am using a different temperature sensor. I also would like to know what port is controlling the leds.

**Comment by VitorFrost** [comment]
Thanks for the info, that is enough for me.  I am using the `pin 4` for 1-wire communication, to connect a temperature sensor (Dallas DS16B20).
I have chosen it because I am housing the sensor inside an straw tube, that is inserted in the reactor! So I restricted the sensor to the encapsulation TO-92, to be digital and works with 3,3V .

**Comment by CamDavidsonPilon** [comment]
> I have chosen it because I am housing the sensor inside an stainless straw tube, that is inserted in the reactor

That's a cool idea!
